spring.application.name=simulapronaf

#Data Base config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Google OAuth
google.oauth.web-client-id=${GOOGLE_WEB_CLIENT_ID}

#Secutiry - JWT
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:certs/app.pub
jwt.private-key-location=classpath:certs/app.key
jwt.public-key-location=classpath:certs/app.pub