spring.application.name=simulapronaf

#Data Base config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

#Migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Google OAuth
google.oauth.web-client-id=${GOOGLE_WEB_CLIENT_ID}

#Secutiry - JWT
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never