INSERT INTO item_linha_credito (
    linha_credito_id,
    titulo,
    resumo,
    descricao,
    publico,
    limite,
    juros,
    prazo_maximo,
    carencia_maxima,
    ordem_exibicao,
    icone,
    ativo,
    data_criacao
)
VALUES
-- Pronaf Custeio
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Custeio'),
    'Bovinocultura de corte',
    'Custeio pecuário para bovinocultura de corte, enquadrado na Faixa IV.',
    'Atividade enquadrada na Faixa IV do Pronaf Custeio, com taxa de juros de 8% ao ano.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    8.00,
    10,
    0,
    1,
    'icone_vaca',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Custeio'),
    'Bovinocultura de leite',
    'Custeio pecuário para bovinocultura de leite, enquadrado na Faixa I.',
    'Atividade enquadrada na Faixa I do Pronaf Custeio, com taxa de juros de 3% ao ano. Para fins de MVP, foi considerado prazo máximo de até 10 meses.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    3.00,
    10,
    0,
    2,
    'icone_leite',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Custeio'),
    'Soja',
    'Custeio agrícola para produção de soja, enquadrado na Faixa IV.',
    'Atividade enquadrada na Faixa IV do Pronaf Custeio, com taxa de juros de 8% ao ano e prazo máximo de até 11 meses.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    8.00,
    11,
    0,
    3,
    'icone_soja',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Custeio'),
    'Arroz',
    'Custeio agrícola para produção de arroz, enquadrado na Faixa I.',
    'Atividade enquadrada na Faixa I do Pronaf Custeio, com taxa de juros de 3% ao ano e prazo máximo de até 11 meses.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    3.00,
    11,
    0,
    4,
    'icone_arroz',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Custeio'),
    'Trigo',
    'Custeio agrícola para produção de trigo, enquadrado na Faixa I.',
    'Atividade enquadrada na Faixa I do Pronaf Custeio, com taxa de juros de 3% ao ano e prazo máximo de até 11 meses.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    3.00,
    11,
    0,
    5,
    'icone_trigo',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Custeio'),
    'Pecuária (Recria e Engorda)',
    'Aquisição de bovinos e bubalinos para recria e engorda, além de compra de insumos e rações.',
    'Financiamento destinado a atividade pecuaria quando o financiamento envolver a aquisição de bovinos e e bibalinos para recria e engorda em sistema extensivo .',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    8.00,
    20,
    0,
    1,
    'icone_vaca',
    TRUE,
    CURRENT_TIMESTAMP
),

-- Pronaf Mais Alimentos - bloco geral até R$ 250 mil / 3% / 10 anos / 3 anos
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Mais Alimentos'),
    'Maquinas e Implementos',
    'Maquinas e Implementos.',
    'Maquinas e Implementos.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    5.00,
    7,
    1,
    1,
    'icone_trator',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Mais Alimentos'),
    'Matrizes e Reprodutores Pecuária de Corte',
    'Matrizes e Reprodutores Pecuária de Corte.',
    'Matrizes e Reprodutores Pecuária de Corte.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    8.00,
    8,
    3,
    2,
    'icone_vaca',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Mais Alimentos'),
    'Construção e Reforma de Moradias Rurais',
    'Construção e Reforma de Moradias Rurais.',
    'Construção e Reforma de Moradias Rurais.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    100000.00,
    8.00,
    10,
    1,
    3,
    'icone_fazenda',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Mais Alimentos'),
    'Caminhonetes e motos',
    'Caminhonetes e motos.',
    'Caminhonetes e motos.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    8.00,
    5,
    0,
    4,
    'icone_caminhonete',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Mais Alimentos'),
    'Melhoramento Genético e Pecuária de Leite',
    'Melhoramento Genético e Pecuária de Leite.',
    'Melhoramento Genético e Pecuária de Leite.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    250000.00,
    3.00,
    10,
    3,
    5,
    'icone_leite',
    TRUE,
    CURRENT_TIMESTAMP
),
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Mais Alimentos'),
    'Atividades Intensivas',
    'Atividades Intensivas.',
    'Atividades Intensivas.',
    'Família com renda bruta anual de enquadramento de até R$ 500 mil.',
    450000.00,
    8.00,
    10,
    3,
    6,
    'icone_porco',
    TRUE,
    CURRENT_TIMESTAMP
),

-- Pronaf Mais Alimentos - renda menor que R$ 150 mil
(
    (SELECT id FROM linha_credito WHERE nome = 'Pronaf Mais Alimentos'),
    'Demais Produtos de Investimento',
    'Demais Produtos de Investimento.',
    'Demais Produtos de Investimento.',
    'Família com renda bruta anual de enquadramento menor que R$ 150 mil.',
    250000.00,
    8.00,
    10,
    3,
    7,
    'icone_silo',
    TRUE,
    CURRENT_TIMESTAMP
);